"""Literal registry metadata for actions implemented by the MCP dispatcher."""

SPECIAL_ACTION_SPECS = {
    "util": {
        "execute_python": {
            "title": "Execute Unreal Python",
            "description": "Execute arbitrary Python in the Unreal editor.",
            "effect": "destructive",
            "risk": "high",
            "result_kind": "json",
            "idempotent": False,
            "supports_preview": False,
            "supports_undo": False,
            "requires_confirmation": True,
            "ue_versions": ["5.6", "5.7", "5.8"],
            "required_plugins": ["PythonScriptPlugin"],
            "input_schema": {
                "type": "object",
                "properties": {"code": {"type": "string", "minLength": 1}},
                "required": ["code"],
                "additionalProperties": False,
            },
            "output_schema": {
                "type": "object",
                "properties": {"success": {"type": "boolean"}},
                "required": ["success"],
                "additionalProperties": True,
            },
        },
        "livecoding_compile": {
            "title": "Compile C++ with Live Coding",
            "description": "Run one Live Coding compilation and return diagnostics.",
            "effect": "write",
            "risk": "high",
            "result_kind": "json",
            "idempotent": False,
            "supports_preview": False,
            "supports_undo": False,
            "requires_confirmation": True,
            "ue_versions": ["5.6", "5.7", "5.8"],
            "required_plugins": [],
            "input_schema": {
                "type": "object",
                "properties": {},
                "additionalProperties": False,
            },
            "output_schema": {
                "type": "object",
                "properties": {"success": {"type": "boolean"}},
                "required": ["success"],
                "additionalProperties": True,
            },
        },
        "search_actions": {
            "title": "Search Unreal Actions",
            "description": "Search Action Registry v2 using text and safety filters.",
            "effect": "read",
            "risk": "low",
            "result_kind": "json",
            "idempotent": True,
            "supports_preview": False,
            "supports_undo": False,
            "requires_confirmation": False,
            "ue_versions": ["5.6", "5.7", "5.8"],
            "required_plugins": [],
            "input_schema": {
                "type": "object",
                "properties": {
                    "query": {"type": "string", "default": ""},
                    "domain": {"type": "string", "default": ""},
                    "effect": {
                        "type": "string",
                        "enum": ["", "read", "write", "destructive"],
                        "default": "",
                    },
                    "risk": {
                        "type": "string",
                        "enum": ["", "low", "medium", "high"],
                        "default": "",
                    },
                    "required_plugin": {"type": "string", "default": ""},
                    "limit": {
                        "type": "integer",
                        "minimum": 1,
                        "maximum": 100,
                        "default": 20,
                    },
                    "cursor": {"type": "string", "default": ""},
                },
                "additionalProperties": False,
            },
            "output_schema": {
                "type": "object",
                "properties": {"success": {"type": "boolean"}},
                "required": ["success"],
                "additionalProperties": True,
            },
        },
        "describe_action": {
            "title": "Describe Unreal Action",
            "description": "Return the complete schema and safety contract for one action.",
            "effect": "read",
            "risk": "low",
            "result_kind": "json",
            "idempotent": True,
            "supports_preview": False,
            "supports_undo": False,
            "requires_confirmation": False,
            "ue_versions": ["5.6", "5.7", "5.8"],
            "required_plugins": [],
            "input_schema": {
                "type": "object",
                "properties": {
                    "domain": {"type": "string", "minLength": 1},
                    "action": {"type": "string", "minLength": 1},
                },
                "required": ["domain", "action"],
                "additionalProperties": False,
            },
            "output_schema": {
                "type": "object",
                "properties": {"success": {"type": "boolean"}},
                "required": ["success"],
                "additionalProperties": True,
            },
        },
        "get_capabilities": {
            "title": "Get Unreal MCP Capabilities",
            "description": "Report server, safety, registry, editor, and plugin capabilities.",
            "effect": "read",
            "risk": "low",
            "result_kind": "json",
            "idempotent": True,
            "supports_preview": False,
            "supports_undo": False,
            "requires_confirmation": False,
            "ue_versions": ["5.6", "5.7", "5.8"],
            "required_plugins": [],
            "input_schema": {
                "type": "object",
                "properties": {},
                "additionalProperties": False,
            },
            "output_schema": {
                "type": "object",
                "properties": {"success": {"type": "boolean"}},
                "required": ["success"],
                "additionalProperties": True,
            },
        },
    },
    "workflow": {
        "plan": {
            "title": "Plan Unreal Workflow",
            "description": "Validate and sign a dependency-ordered Unreal workflow plan.",
            "effect": "read",
            "risk": "low",
            "result_kind": "json",
            "idempotent": True,
            "supports_preview": True,
            "supports_undo": False,
            "requires_confirmation": False,
            "ue_versions": ["5.6", "5.7", "5.8"],
            "required_plugins": [],
            "examples": [
                {
                    "action": "plan",
                    "params": {
                        "operations": [
                            {
                                "id": "create-player",
                                "domain": "blueprint",
                                "action": "create_blueprint",
                                "params": {
                                    "asset_path": "/Game/BP_Player"
                                },
                                "depends_on": [],
                            }
                        ]
                    },
                }
            ],
            "input_schema": {
                "type": "object",
                "properties": {
                    "operations": {
                        "type": "array",
                        "minItems": 1,
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": {"type": "string", "minLength": 1},
                                "domain": {"type": "string", "minLength": 1},
                                "action": {"type": "string", "minLength": 1},
                                "params": {"type": "object", "default": {}},
                                "depends_on": {
                                    "type": "array",
                                    "items": {"type": "string", "minLength": 1},
                                    "default": [],
                                },
                            },
                            "required": ["id", "domain", "action"],
                            "additionalProperties": False,
                        },
                    },
                    "allow_non_undoable": {
                        "type": "boolean",
                        "default": False,
                    },
                },
                "required": ["operations"],
                "additionalProperties": False,
            },
            "output_schema": {
                "type": "object",
                "properties": {"success": {"type": "boolean"}},
                "required": ["success"],
                "additionalProperties": True,
            },
        },
        "apply": {
            "title": "Apply Unreal Workflow",
            "description": "Execute a confirmed workflow with progress and recovery.",
            "effect": "write",
            "risk": "high",
            "result_kind": "json",
            "idempotent": False,
            "supports_preview": False,
            "supports_undo": True,
            "requires_confirmation": True,
            "ue_versions": ["5.6", "5.7", "5.8"],
            "required_plugins": [],
            "input_schema": {
                "type": "object",
                "properties": {
                    "plan_id": {"type": "string", "minLength": 1},
                    "confirmation_token": {
                        "type": "string",
                        "minLength": 1,
                    },
                    "wait_for_completion": {
                        "type": "boolean",
                        "default": False,
                    },
                },
                "required": ["plan_id", "confirmation_token"],
                "additionalProperties": False,
            },
            "output_schema": {
                "type": "object",
                "properties": {"success": {"type": "boolean"}},
                "required": ["success"],
                "additionalProperties": True,
            },
        },
        "get": {
            "title": "Get Unreal Workflow",
            "description": "Return a workflow plan and its latest runtime state.",
            "effect": "read",
            "risk": "low",
            "result_kind": "json",
            "idempotent": True,
            "supports_preview": False,
            "supports_undo": False,
            "requires_confirmation": False,
            "ue_versions": ["5.6", "5.7", "5.8"],
            "required_plugins": [],
            "input_schema": {
                "type": "object",
                "properties": {
                    "plan_id": {"type": "string", "minLength": 1}
                },
                "required": ["plan_id"],
                "additionalProperties": False,
            },
            "output_schema": {
                "type": "object",
                "properties": {"success": {"type": "boolean"}},
                "required": ["success"],
                "additionalProperties": True,
            },
        },
        "cancel": {
            "title": "Cancel Unreal Workflow",
            "description": "Request cancellation at the next safe workflow boundary.",
            "effect": "write",
            "risk": "medium",
            "result_kind": "json",
            "idempotent": True,
            "supports_preview": False,
            "supports_undo": False,
            "requires_confirmation": False,
            "ue_versions": ["5.6", "5.7", "5.8"],
            "required_plugins": [],
            "input_schema": {
                "type": "object",
                "properties": {
                    "plan_id": {"type": "string", "minLength": 1}
                },
                "required": ["plan_id"],
                "additionalProperties": False,
            },
            "output_schema": {
                "type": "object",
                "properties": {"success": {"type": "boolean"}},
                "required": ["success"],
                "additionalProperties": True,
            },
        },
        "undo": {
            "title": "Undo Unreal Workflow",
            "description": "Guard and undo the committed transaction bound to a workflow.",
            "effect": "destructive",
            "risk": "high",
            "result_kind": "json",
            "idempotent": False,
            "supports_preview": False,
            "supports_undo": False,
            "requires_confirmation": True,
            "ue_versions": ["5.6", "5.7", "5.8"],
            "required_plugins": [],
            "input_schema": {
                "type": "object",
                "properties": {
                    "plan_id": {"type": "string", "minLength": 1},
                    "undo_token": {"type": "string", "minLength": 1},
                },
                "required": ["plan_id", "undo_token"],
                "additionalProperties": False,
            },
            "output_schema": {
                "type": "object",
                "properties": {"success": {"type": "boolean"}},
                "required": ["success"],
                "additionalProperties": True,
            },
        },
    },
}
